# Input name, age (in years), weight (in kgs) and height (in meters)
print("What is your name human?")
name = input()
print("So, your name is "+ name +".")
print()
print("Tell me "+ name +". How old are you? (in years)")
age = int(input())
print()
print("So "+ name +" - Age = "+ str(age) +" years, how much do you weigh? (in KGs)")
weight = int(input())
print("Holy Moly! And how tall are you? (in meters)")
height = float(input())
bmi = float(weight/(height*height))
print("So, "+ name +", my computers are telling me that a "+ str(age) +" year old, weighing "+ str(weight) +"kg, standing at "+ str(height) +"meters has a BMI of "+ str(round(bmi, 1)) +".")