# Display a box
print("##########")
print("#        #")
print("#        #")
print("##########")
print()
print()
print("       _______        ")
print("     _/       \\_      ")
print("    / |       | \\     ")
print("   /  |__   __|  \\    ")
print("  |__/((o| |o))\__|   ")
print("  |      | |      |   ")
print("  |\     |_|     /|   ")
print("  | \           / |   ")
print("   \\| /  ___  \ |/    ")
print("    \\ | / _ \ | /     ")
print("     \\_________/      ")
print("      _|_____|_       ")
print(" ____|_________|____  ")
print("/                   \\ ")
