print("Please enter a 5 digit number:")
number = input()
print()
print("Please choose from one of the following options:")
print()
print("1) Display ASCII Triangle - display the number in an ascii art triangle.")
print("2) Display Left Digits Triangle - display digits of the number so that they form a triangle aligned on the left.")
print("3) Display Right Triangle – display the digits of the number so that they form a triangle aligned to the right.")
print()
print("Please choose by entering a number 1 to 3:")
option = int(input())